// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Accio",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Accio",
            targets: ["AppModule"],
            bundleIdentifier: "codes.chirag.Accio",
            teamIdentifier: "8AJAPGUS29",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .camera),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Accio uses the camera to find objects around you in real time.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/detectionModel.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)